name: Install AWS CLI
description: "Install the AWS CLI"
runs:
  using: "composite"
  steps:
    - name: Download AWS CLI
      run: sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      shell: bash
    - name: Unzip AWS CLI
      run: sudo unzip -qq awscliv2.zip
      shell: bash
    - name: Install AWS CLI
      run: sudo ./aws/install
      shell: bash
